### ISSUE TITLE
Fails on node v4

### ISSUE THREAD

**Issue by hueniverse** [hapijs/wreck#104]
```
> lab -i 22

_http_server.js:515
  this._handle.readStart();
              ^

TypeError: Cannot read property 'readStart' of null
    at Socket.onSocketResume (_http_server.js:515:15)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at resume_ (_stream_readable.js:712:10)
    at doNTCallback2 (node.js:429:9)
    at process._tickDomainCallback (node.js:384:17)
```

Also 84 and 85.

**Comment by geek** [comment]
I was able to reproduce this issue without wreck... here is the issue:


```
var Http = require('http');
var Fs = require('fs');
var Url = require('url');

var server = Http.createServer(function (req, res) {

    res.writeHead(200);
    res.end();
});


server.listen(8080);

var uri = Url.parse('http://localhost:8080/');
uri.method = 'post';
var req = Http.request(uri);



var stream = Fs.createReadStream(__dirname + '/images/wreck.png');
stream.pipe(req);
```


There seems to be a limit around 16kb on the size of payloads that work vs break.

**Comment by kanongil** [comment]
This seems like a node issue, though not something that likely to happen under normal circumstances.

As far as I can tell, it happens if the reply is processed before the request is completed. In your example it can be "fixed" by scheduling `res.end()` on `process.nextTick()`.

**Comment by geek** [comment]
I can change the tests to be under 16kb when sending a payload, which will fix the tests.

**Comment by kanongil** [comment]
This fixes all tests for me:
```diff
diff --git a/test/index.js b/test/index.js
index 74a1dea..d70ba13 100755
--- a/test/index.js
+++ b/test/index.js
@@ -535,17 +535,20 @@ describe('request()', function () {
         var gen = 0;
         var server = Http.createServer(function (req, res) {
 
-            if (!gen++) {
-                res.writeHead(307, { 'Location': '/' });
-                res.end();
-            }
-            else {
-                res.writeHead(200, { 'Content-Type': 'text/plain' });
-                Wreck.read(req, null, function (err, res2) {
+            process.nextTick(function () {
 
-                    res.end(res2);
-                });
-            }
+                if (!gen++) {
+                    res.writeHead(307, { 'Location': '/' });
+                    res.end();
+                }
+                else {
+                    res.writeHead(200, { 'Content-Type': 'text/plain' });
+                    Wreck.read(req, null, function (err, res2) {
+
+                        res.end(res2);
+                    });
+                }
+            });
         });
 
         server.listen(0, function () {
```

**Comment by Marsup** [comment]
Isn't it related to https://github.com/nodejs/node/pull/2355 ?

**Comment by hueniverse** [comment]
The real question is if this indicates a problem with node v4 or just something minor we can fix in our own tests. The existing failing code looks legit to me.

**Comment by Marsup** [comment]
@geek and @lloydbenson talked to some core contributors at nodeconfeu and should be working on a test case soon, that's probably up to node to fix it.

**Comment by geek** [comment]
I logged an issue here: https://github.com/nodejs/node/issues/2821

**Comment by geek** [comment]
Workaround for issue is in https://github.com/hapijs/wreck/commit/6633ff5061c4622e8c164c3f11fc40dade05c0db
