### ISSUE TITLE
Unusable stack traces

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/wreck#168]
With the new Boom error thingy when I get a 404 from a `Wreck.get` I get this stacktrace
```js
 Error: Response Error: Not Found
     at /Users/adri/myproject/node_modules/wreck/lib/index.js:524:38
     at finish (/Users/adri/myproject/node_modules/wreck/lib/index.js:344:20)
     at wrapped (/Users/adri/myproject/node_modules/hoek/lib/index.js:871:20)
     at onReaderFinish (/Users/adri/myproject/node_modules/wreck/lib/index.js:415:16)
     at g (events.js:260:16)
     at emitNone (events.js:72:20)
     at emit (events.js:166:7)
     at finishMaybe (_stream_writable.js:482:14)
     at afterWrite (_stream_writable.js:356:3)
     at nextTickCallbackWithManyArgs (node.js:533:18)
     at process._tickDomainCallback (node.js:472:17)
     at process.fallback (/Users/adri/myproject/node_modules/async-listener/index.js:482:15)
```
Which is worth nothing as you can see.
The reason is this `Boom.create` https://github.com/hapijs/wreck/blob/111a59a8cb75828de394e46455f79ed7de7f7a32/lib/index.js#L524
which in itself does a `captureStackTrace` https://github.com/hapijs/boom/blob/3d30c69faf6733a1604b400df71ed4781799a032/lib/index.js#L98

Would it be possible to pass an Error object to the `Boom.create` so it bypasses the `captureStackTrace`?

**Comment by geek** [comment]
@AdriVanHoudt I like your idea of creating a new error object and passing that to create.

**Comment by AdriVanHoudt** [comment]
Hmm I tried passing an error but it seems that that does nothing to the stack.
I think the `captureStackTrace` from Boom is actually to make sure Boom does not show up in the stack, which is what you'd want.
Passing an error seems to be the more correct thing to do though. (I will do a PR for that)

I'm not sure how to approach my problem then :/

**Comment by kanongil** [comment]
@AdriVanHoudt I don't think what you desire is possible.

You would need to create your own error in the callback, to include it in the stack trace.

**Comment by AdriVanHoudt** [comment]
hmm I see
