### ISSUE TITLE
Race condition when reading gzipped response

### ISSUE THREAD

**Issue by marco-ramirez** [hapijs/wreck#219]
I get `Error: Payload stream closed prematurely` when a gzip response is "too big". I've created a script to reproduce the error case at the following repo https://github.com/marco-ramirez/wreck-premature. This is the output from that script:

```
Server started http://127.0.0.1:50632
Received a payload of 10000 bytes
Received a gzipped payload of 10000 bytes
Received a payload of 100000 bytes
Error requesting a gzipped payload of 100000 bytes:
Error: Payload stream closed prematurely
    at IncomingMessage.onResAborted (/Users/marco/dev/wreck-premature/node_modules/wreck/lib/index.js:444:32)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (_http_client.js:359:11)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

If I comment out https://github.com/hapijs/wreck/blob/master/lib/index.js#L448. The error is not thrown and this is the output:

```
Server started http://127.0.0.1:51792
Received a payload of 10000 bytes
Received a gzipped payload of 10000 bytes
Received a payload of 100000 bytes
Received a gzipped payload of 100000 bytes
```
OS: macOS Sierra 10.12.6
Node.js version: v9.9.0

**Comment by marco-ramirez** [comment]
This has been fixed in v14.1.0 by https://github.com/hapijs/wreck/commit/5493ae1fdcf85218a0dbd2c25789e41347f319d7.
