### ISSUE TITLE
How to present the client certificate for authentication using wreck?

### ISSUE THREAD

**Issue by u-r-v** [hapijs/wreck#221]
I used the below logic to present the certificate from client side.
`let options = { json: "force", headers, payload: payload};
    const agentOptions = {
      key: fs.readFileSync("./config/cert.pem"),
      cert: fs.readFileSync("./config/key.pem"),
      ca: [fs.readFileSync("./config/ca-cert.pem")]
    };
    options = {options, agentOptions};`

But am getting the below error.
`HTTP 15221: SOCKET ERROR: write EPROTO 140735592244096:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1500:SSL alert number 40
140735592244096:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:659:
 Error: write EPROTO 140735592244096:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1500:SSL alert number 40
140735592244096:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:659:

    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
`

Anyone had faced the similar issue?

**Comment by hueniverse** [comment]
Closing due to lack of activity.
