### ISSUE TITLE
Unable to GET a server that listens to IPv6 address. ETIMEDOUT

### ISSUE THREAD

**Issue by sergibondarenko** [hapijs/wreck#276]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: v13.8.0
* *module version with issue*: @hapi/wreck v17.0.0 
* *last module version without issue*: I didn't try with IPv6 before.
* *environment* (e.g. node, browser, native): NodeJS
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi powered web application
* *any other relevant information*: macOS 10.15.4

#### What are you trying to achieve or the steps to reproduce?

I want to send a GET request to a server that listens to an IPv6 address. The request fails with ETIMEDOUT.

#### What was the result you got?
Please follow the **Steps to reproduce** section to see the results.
 
#### Steps to reproduce
1. Create **server.js**
```js
const http = require('http');

http.createServer({}, function(req, res) {
  res.writeHead(200);
  res.end('hello world\n');
}).listen(3000, '::1');
```

2. Create **client.js**
```js
const wreck = require('@hapi/wreck');

wreck
  .get('http://[::1]:3000')
  .then(console.log)
  .catch(console.error);
```

3. Run **server.js**
```
$ NODE_DEBUG="net,http" node server.js 
NET 57621: setupListenHandle ::1 3000 6 0 undefined
NET 57621: setupListenHandle: create a handle
NET 57621: bind to ::1
```

4. Run **client.js**. See no "hello world" response and `NET 57628: _read wait for connection`. Wait some time and you will see the ETIMEDOUT error.

<details>

```
$ NODE_DEBUG="net,http" node wreck_client.js
HTTP 57628: call onSocket 0 0
HTTP 57628: createConnection [::1]:3000: {
  setHost: false,
  host: '[::1]',
  origin: 'http://[::1]:3000',
  searchParams: URLSearchParams {}, 
  protocol: 'http:',
  hostname: '[::1]',
  hash: '',
  search: '',
  pathname: '/',
  path: null,
  href: 'http://[::1]:3000/',
  port: 3000,
  method: 'GET',
  headers: { host: '[::1]:3000' },
  agent: Agent {
    _events: [Object: null prototype] {
      free: [Function (anonymous)],
      newListener: [Function: maybeEnableKeylog]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    defaultPort: 80,
    protocol: 'http:',
    options: { maxSockets: Infinity, path: null },
    requests: {},
    sockets: { '[::1]:3000:': [] },
    freeSockets: {},
    keepAliveMsecs: 1000,
    keepAlive: false,
    maxSockets: Infinity,
    maxFreeSockets: 256,
    [Symbol(kCapture)]: false
  },
  maxSockets: Infinity,
  servername: '',
  _agentKey: '[::1]:3000:'
}
NET 57628: createConnection [
  {
    setHost: false,
    host: '[::1]',
    origin: 'http://[::1]:3000',
    searchParams: URLSearchParams {},
    protocol: 'http:',
    hostname: '[::1]',
    hash: '',
    search: '',
    pathname: '/',
    path: null,
    href: 'http://[::1]:3000/',
    port: 3000,
    method: 'GET',
    headers: { host: '[::1]:3000' },
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      [Symbol(kCapture)]: false
    },
    maxSockets: Infinity,
    servername: '',
    _agentKey: '[::1]:3000:',
    encoding: null
  },
  [Function: oncreate],
  [Symbol(normalizedArgs)]: true
]
NET 57628: pipe false null
NET 57628: connect: find host [::1] 
NET 57628: connect: dns options { family: undefined, hints: 1024 }
HTTP 57628: sockets [::1]:3000: 1
HTTP 57628: outgoing message end.   
(node:57628) Warning: Setting the NODE_DEBUG environment variable to 'http' can expose sensitive data (such as passwords, tokens and authentication headers) in the resulting log.
NET 57628: _read
NET 57628: _read wait for connection

// WAIT SOME TIME AND YOU WILL SEE THE LOG BELOW
NET 57628: afterConnect
NET 57628: destroy
NET 57628: close
NET 57628: close handle
HTTP 57628: SOCKET ERROR: connect ETIMEDOUT 54.72.52.58:3000 Error: connect ETIMEDOUT 54.72.52.58:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
Error: connect ETIMEDOUT 54.72.52.58:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '54.72.52.58',
  port: 3000,
  trace: [ { method: 'GET', url: 'http://[::1]:3000' } ],
  isBoom: true,
  isServer: true,
  data: null,
  output: {
    statusCode: 502,
    payload: {
      message: 'Client request error: connect ETIMEDOUT 54.72.52.58:3000',
      statusCode: 502,
      error: 'Bad Gateway'
    },
    headers: {}
  }
}
NET 57628: emit close
HTTP 57628: CLIENT socket onClose   
HTTP 57628: removeSocket [::1]:3000: writable: false
HTTP 57628: HTTP socket close
```
</details>

5. Look at the **server.js** log. There are no new messages. It looks like Wreck can't reach the server.js.

#### What result did you expect?

I expect to have the server responding with the "hello world" to my HTTP request.

<details>
<summary>For example</summary>

1. Curl
Run **curl** test. See there is "hello world" response.
```
$ curl -v -k -6 "http://[::1]:3000" 
*   Trying ::1...
* TCP_NODELAY set
* Connected to ::1 (::1) port 3000 (#0)
> GET / HTTP/1.1
> Host: [::1]:3000
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Mon, 11 May 2020 08:00:55 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
< 
hello world
* Connection #0 to host ::1 left intact
* Closing connection 0
```

Look at **server.js** log. You see, there is the log.

```
NET 57635: onconnection
NET 57635: _read
NET 57635: Socket._read readStart
HTTP 57635: SERVER new http connection
HTTP 57635: write ret = true
HTTP 57635: outgoing message end.
HTTP 57635: SERVER socketOnParserExecute 74
HTTP 57635: resetHeadersTimeoutOnReqEnd
NET 57635: _final: not ended, call shutdown()
NET 57635: afterShutdown destroyed=false ReadableState {
  objectMode: false,
  highWaterMark: 16384,
  buffer: BufferList { head: null, tail: null, length: 0 },
  length: 0,
  pipes: null,
  pipesCount: 0,
  flowing: true,
  ended: true,
  endEmitted: true,
  reading: false,
  sync: false,
  needReadable: false,
  emittedReadable: false,
  readableListening: false,
  resumeScheduled: false,
  paused: false,
  emitClose: false,
  autoDestroy: false,
  destroyed: false,
  defaultEncoding: 'utf8',
  awaitDrain: 0,
  readingMore: false,
  decoder: null,
  encoding: null }
NET 57635: readableState ended, destroying
NET 57635: destroy
NET 57635: close
NET 57635: close handle
NET 57635: has server
NET 57635: SERVER _emitCloseIfDrained
NET 57635: SERVER handle? true   connections? 0
NET 57635: emit close
HTTP 57635: server socket close
```

2. NodeJS HTTP request
Create a new **client.js**, use NodeJS HTTP module.
```
const http = require('http');

const options = {
  host: '::1',
  port: 3000,
  path: '/',
  method: 'GET',
};

const req = http.request(options, function(res) {
  console.log("Client A statusCode: ", res.statusCode);
  console.log("Client A headers: ", res.headers);
  
  res.on('data', function(d) {
    process.stdout.write(d);
  });
});

req.end();

req.on('error', function(e) {
  console.error(e);
});
```
Run **client.js**. See the "hello world" response.
```
$ NODE_DEBUG="net,http" node client.js
HTTP 57729: call onSocket 0 0
HTTP 57729: createConnection ::1:3000: {
  host: '::1',
  port: 3000,
  path: null,
  method: 'GET',
  servername: '',
  _agentKey: '::1:3000:'
} 
NET 57729: createConnection [
  {
    host: '::1',
    port: 3000,
    path: null,
    method: 'GET',
    servername: '',
    _agentKey: '::1:3000:',
    encoding: null
  },
  [Function: oncreate],
  [Symbol(normalizedArgs)]: true
] 
NET 57729: pipe false null
HTTP 57729: sockets ::1:3000: 1
HTTP 57729: outgoing message end.
(node:57729) Warning: Setting the NODE_DEBUG environment variable to 'http' can expose sensitive data (such as passwords, tokens and authentication headers) in the resulting log.
NET 57729: _read
NET 57729: _read wait for connection
NET 57729: afterConnect
NET 57729: _read
NET 57729: Socket._handle.readStart
HTTP 57729: AGENT incoming response!
Client A statusCode:  200
Client A headers:  {
  date: 'Mon, 11 May 2020 08:07:12 GMT',
  connection: 'close',
  'transfer-encoding': 'chunked'
}
hello world
NET 57729: _read
HTTP 57729: AGENT socket.destroySoon()
NET 57729: _final: not ended, call shutdown()
NET 57729: destroy
NET 57729: close
NET 57729: close handle
NET 57729: afterShutdown destroyed=true ReadableState {
  objectMode: false,
  highWaterMark: 16384,
  buffer: BufferList { head: null, tail: null, length: 0 },
  length: 0,
  pipes: [],
  flowing: true,
  ended: true,
  endEmitted: true,
  reading: false,
  sync: false,
  needReadable: false,
  emittedReadable: false,
  readableListening: false,
  resumeScheduled: false,
  errorEmitted: false,
  emitClose: false,
  autoDestroy: false,
  destroyed: true,
  defaultEncoding: 'utf8',
  awaitDrainWriters: null,
  multiAwaitDrain: false,
  readingMore: false,
  decoder: null,
  encoding: null,
  [Symbol(kPaused)]: false
}
NET 57729: emit close
HTTP 57729: CLIENT socket onClose   
HTTP 57729: removeSocket ::1:3000: writable: false
HTTP 57729: HTTP socket close
```
Look at **server.js** log
```
NET 57728: onconnection
NET 57728: _read
NET 57728: Socket._read readStart
HTTP 57728: SERVER new http connection
HTTP 57728: write ret = true
HTTP 57728: outgoing message end.
HTTP 57728: SERVER socketOnParserExecute 55
NET 57728: _final: not ended, call shutdown()
HTTP 57728: resetHeadersTimeoutOnReqEnd
NET 57728: afterShutdown destroyed=false ReadableState {
  objectMode: false,
  highWaterMark: 16384,
  buffer: BufferList { head: null, tail: null, length: 0 },
  length: 0,
  pipes: null,
  pipesCount: 0,
  flowing: true,
  ended: false,
  endEmitted: false,
  reading: true,
  sync: false,
  needReadable: true,
  emittedReadable: false,
  readableListening: false,
  resumeScheduled: false,
  paused: false,
  emitClose: false,
  autoDestroy: false,
  destroyed: false,
  defaultEncoding: 'utf8',
  awaitDrain: 0,
  readingMore: false,
  decoder: null,
  encoding: null }
NET 57728: destroy
NET 57728: close
NET 57728: close handle
NET 57728: has server
NET 57728: SERVER _emitCloseIfDrained
NET 57728: SERVER handle? true   connections? 0
NET 57728: emit close
HTTP 57728: server socket close
```
</details>

**Comment by kanongil** [comment]
This appears to be a bug with the url-string to request options logic [here](https://github.com/hapijs/wreck/blob/923f1899a63676fb167b1794bb75a9527666263c/lib/index.js#L646-L669).

It doesn't account for IPv6 style IP-addresses, and convert it as [the built-in logic does](https://github.com/nodejs/node/blob/8a6fab02adab2de05f6e864847f96b0924be0840/lib/internal/url.js#L1271-L1290).

**Comment by devinstewart** [comment]
It appears Travis has gotten the best of me in PR #281.  Seemed pretty straight forward as @kanongil pretty much laid out the answer, but my new test is failing in Travis.

I have run the tests on a MacOS, Windows, and Linux (Ubuntu 16.04 Xenial) and they all pass.  

I also recreated the _steps to reproduce_, and all seemed well with the one line code change.

Any Travis assistance would be appreciated.

**Comment by lloydbenson** [comment]
We moved to github actions now, maybe rebase and try again to see if that helps. I haven't had a chance to read the doc yet with regards to ipv6.

**Comment by devinstewart** [comment]
Indeed everything passes fine with the rebase.  Approve comment at your leisure.

**Comment by geek** [comment]
Fixed by https://github.com/hapijs/wreck/pull/281
