### ISSUE TITLE
 Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by StarpTech** [hapijs/wreck#84]
Hi
when I run some tests (lab) one after the other this `warning` is thrown.

```
  ..........(node) warning: possible EventEmitter memory leak detected. 11 response listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:179:15)
    at E:\Vagrant\Ubuntu1404\Bodyclub24-WebApp\api\node_modules\good\lib\monitor.js:172:15
    at done (E:\Vagrant\Ubuntu1404\Bodyclub24-WebApp\api\node_modules\items\lib\index.js:30:25)
    at internals.GoodFile.init (E:\Vagrant\Ubuntu1404\Bodyclub24-WebApp\api\node_modules\good-file\lib\index.js:157:5)
    at E:\Vagrant\Ubuntu1404\Bodyclub24-WebApp\api\node_modules\good\lib\monitor.js:149:18
    at iterate (E:\Vagrant\Ubuntu1404\Bodyclub24-WebApp\api\node_modules\items\lib\index.js:35:13)
    at Object.exports.serial (E:\Vagrant\Ubuntu1404\Bodyclub24-WebApp\api\node_modules\items\lib\index.js:38:9)
    at internals.Monitor.start (E:\Vagrant\Ubuntu1404\Bodyclub24-WebApp\api\node_modules\good\lib\monitor.js:124:11)
    at Object.exports.register (E:\Vagrant\Ubuntu1404\Bodyclub24-WebApp\api\node_modules\good\lib\index.js:17:20)
    at E:\Vagrant\Ubuntu1404\Bodyclub24-WebApp\api\node_modules\hapi\lib\plugin.js:242:14
    at iterate (E:\Vagrant\Ubuntu1404\Bodyclub24-WebApp\api\node_modules\items\lib\index.js:35:13)
    at Object.exports.serial (E:\Vagrant\Ubuntu1404\Bodyclub24-WebApp\api\node_modules\items\lib\index.js:38:9)
    at internals.Plugin.register (E:\Vagrant\Ubuntu1404\Bodyclub24-WebApp\api\node_modules\hapi\lib\plugin.js:224:11)
    at Object.exports.register (E:\Vagrant\Ubuntu1404\Bodyclub24-WebApp\api\lib\index.js:61:10)
    at E:\Vagrant\Ubuntu1404\Bodyclub24-WebApp\api\node_modules\hapi\lib\plugin.js:242:14
    at iterate (E:\Vagrant\Ubuntu1404\Bodyclub24-WebApp\api\node_modules\items\lib\index.js:35:13)
    at Object.exports.serial (E:\Vagrant\Ubuntu1404\Bodyclub24-WebApp\api\node_modules\items\lib\index.js:38:9)
    at internals.Plugin.register (E:\Vagrant\Ubuntu1404\Bodyclub24-WebApp\api\node_modules\hapi\lib\plugin.js:224:11)
    at Object.exports.initServer (E:\Vagrant\Ubuntu1404\Bodyclub24-WebApp\api\test\_utils.js:199:10)
    at E:\Vagrant\Ubuntu1404\Bodyclub24-WebApp\api\test\auth\local-reset-password.js:16:11
    at Immediate._onImmediate (C:\Users\dustin\AppData\Roaming\npm\node_modules\lab\lib\runner.js:445:17)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```
good: 6.1.2,
good-console: 5.0.0
hapi: 8.4.0
NodeJs: v0.12.2

thanks!

**Comment by StarpTech** [comment]
Please delete. Moved to https://github.com/hapijs/good/issues/341
